server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-composite
          uri: lb://product-composite-service
          predicates:
            - Path=/v1/product-composite/**
        - id: product-composite-swagger
          uri: lb://product-composite-service
          predicates:
            - Path=/openapi/**
        - id: eureka-web-start
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-web-others
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: config-server
          uri: http://localhost:8888
          predicates:
            - Path=/config/**
          filters: 
            - RewritePath=/config/(?<segment>.*),/$\{segment}
app:
  eureka:
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@eureka:8761/eureka/"
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: debug
    org.springframework.cloud.gateway: debug