server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: password
    key-alias: localhost
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  boot:
    admin:
      client:
        url: http://metric-service:8889
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  config:
    activate:
      on-profile: k8s
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-composite
          uri: http://product-composite-service:8080
          predicates:
            - Path=/v1/product-composite/**
        - id: product-composite-swagger
          uri: http://product-composite-service:8080
          predicates:
            - Path=/openapi/**
        - id: eureka-web-start
          uri: http://eureka-service:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: eureka-web-others
          uri: http://eureka-service:8761
          predicates:
            - Path=/eureka/**
        - id: config-server
          uri: http://config-service:8888
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*),/$\{segment}
app:
  eureka:
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@eureka-service:8761/eureka/"
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: debug
    org.springframework.cloud.gateway: debug
