server:
  port: 8080
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  boot:
    admin:
      client:
        url: http://metric-service:8889
        instance:
          metadata:
            name: product-composite-service
  application:
    name: product-composite
  config:
    activate:
      on-profile: k8s
  cloud:
    stream:
      bindings:
        output-out-0:
          destination: product
        output-out-1:
          destination: review
        output-out-2:
          destination: recommendation
      kafka:
        binder:
          brokers: kafka-service
springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: ma.errabi.microservice.composite
  pathsToMatch: /**

app:
  product-service:
    host: http://product-service:8081
  review-service:
    host: http://review-service:8082
  recommendation-service:
    host: http://recommendation-service:8083
  eureka:
    username: admin
    password: admin

api:
  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...
    termsOfService: MY TERMS OF SERVICE
    license: MY LICENSE
    licenseUrl: MY LICENSE URL
    externalDocDesc: MY WIKI PAGE
    externalDocUrl: MY WIKI URL
    contact:
      name: NAME OF CONTACT
      url: URL TO CONTACT
      email: contact@mail.com
eureka:
  client:
    service-url:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@eureka-service:8761/eureka/"
resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 4
        waitDurationInOpenState: 5s
        ignore-exceptions:
          - ma.errabi.sdk.exception.EntityNotFoundException
  retry:
    instances:
      productServiceRetry:
        maxAttempts: 3
        waitDuration: 1s
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    circuitBreakers:
      enabled: true
logging:
  level:
    org.springframework.cloud.client.loadbalancer: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
