spring:
  boot:
    admin:
      client:
        url: http://metric-server:8889
  application:
    name: product-service
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: product-db
  cloud:
    stream:
      bindings:
        deleteProductConsumer-in-0:
          destination: product
          group: product-consumer-group
      kafka:
        binder:
          brokers: kafka
          consumer-properties:
            enable.auto.commit: false
server:
  port: 8080

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: *
app:
  eureka:
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@eureka:8761/eureka/"
