spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  boot:
    admin:
      client:
        url: http://metric-service:8889
  application:
    name: product-service
  config:
    activate:
      on-profile: k8s
  data:
    mongodb:
      host: mongodb-service
      port: 27017
      database: product-db
  cloud:
    stream:
      bindings:
        deleteProductConsumer-in-0:
          destination: product
          group: product-consumer-group
      kafka:
        binder:
          brokers: kafka-service:9092
          consumer-properties:
            enable.auto.commit: false
server:
  port: 8081
  shutdown: graceful
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
app:
  eureka:
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@eureka-service:8761/eureka/"
