
server:
  port: 8010
  forward-headers-strategy: framework
spring:
  application:
    name: product-composite
  cloud:
    stream:
      bindings:
        output-out-0:
          destination: product
        output-out-1:
          destination: review
        output-out-2:
          destination: recommendation
      kafka:
        binder:
          brokers: localhost:9092

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: ma.errabi.microservice.composite
  pathsToMatch: /**

app:
  product-service:
    host: http://PRODUCT-SERVICE
  review-service:
    host: http://REVIEW-SERVICE
  recommendation-service:
    host: http://RECOMMENDATION-SERVICE
  eureka:
    username: admin
    password: admin
api:
  common:
    version: 1.0.0
    title: Sample API
    description: Description of the API...
    termsOfService: MY TERMS OF SERVICE
    license: MY LICENSE
    licenseUrl: MY LICENSE URL
    externalDocDesc: MY WIKI PAGE
    externalDocUrl: MY WIKI URL
    contact:
      name: NAME OF CONTACT
      url: URL TO CONTACT
      email: contact@mail.com

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@127.0.0.1:8761/eureka/"
    initial-instance-info-replication-interval-seconds: 0
    registry-fetch-interval-seconds: 5
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true

logging:
  level:
    org.springdoc: DEBUG
