server:
  port: 8083
  shutdown: graceful
spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  boot:
    admin:
      client:
        url: http://metric-service:8889
  application:
    name: recommendation-service
  datasource:
    url: jdbc:postgresql://ep-curly-thunder-a5bovt5y.us-east-2.aws.neon.tech:5432/review?schema=recommendation
    username: review
    password: RVlCws5U0QTu
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  cloud:
    stream:
      bindings:
        deleteRecommendationConsumer-in-0:
          destination: recommendation
          group: recommendation-consumer-group
      kafka:
        binder:
          brokers: kafka-service:9092
          consumer-properties:
            enable.auto.commit: false
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-service:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"
app:
  eureka:
    username: admin
    password: admin
eureka:
  client:
    serviceUrl:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@eureka-service:8761/eureka/"
