spring:
  application:
    name: recommendation-service
  config:
    activate:
      on-profile: docker
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        multiplier: 1.3
        max-interval: 10000
        max-attempts: 20
      uri: http://config-server:8888
      enabled: true