server:
  port: 8080
spring:
  boot:
    admin:
      client:
        url: http://metric-server:8889
  application:
    name: review-service
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://ep-curly-thunder-a5bovt5y.us-east-2.aws.neon.tech:5432/review
    username: review
    password: RVlCws5U0QTu
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  cloud:
    stream:
      bindings:
        deleteReviewConsumer-in-0:
          destination: review
          group: review-consumer-group
      kafka:
        binder:
          brokers: kafka
          consumer-properties:
            enable.auto.commit: false
app:
  eureka:
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: "http://${app.eureka.username}:${app.eureka.password}@eureka:8761/eureka/"
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: *
